config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  resources :posts
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  resources :categories
  resources :users, only: [ :show, :edit ]
  get 'static_pages/home'
  get 'static_pages/contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  validates :name, presence: true
  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category

  validates :title, :summary, :body, presence: true
  mount_uploader :image, ImageUploader

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_validation :set_name, on: :create
  before_validation :set_phone, on: :create

  private

  def set_name
    self.name = "Person#{rand(1000)}" if self.name.blank?
  end

  def set_phone
    self.phone = "No phone" if self.phone.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(:password, :password_confirmation, :current_password)
    }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, success: 'Category was successfully created'
    else
      @categories = Category.all.order(:name)
      flash.now[:danger] = 'Category was not created'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path, success: 'Category was successfully updated'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash.now[:danger] = 'Category was not updated'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, success: 'Category was successfully deleted'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok } }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Post was successfully created'
    else
      flash.now[:danger] = 'Post was not created'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Post was successfully updated'
    else
      flash.now[:danger] = 'Post was not created'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, success: 'Post was successfully deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :image_cache, :all_tags, :category_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def contacts
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [ :show, :edit ]

  def show
  end

  def edit
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb(category)
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: "breadcrumb-item active")
    result.join('').html_safe
  end

  def user_avatar(user)
    # TODO
    asset_path('ruby.svg')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group" >
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('.common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buttons_panel">
  <%= link_to 'New category', new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Parent category</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= category.name %></td>
          <td><%= category.parent.name if category.parent.present? %></td>
          <td>
            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<%= render 'shared/breadcrumb', category: @category %>

<h1><%= @category.name %></h1>

<section id="posts">
  <%= render @posts %>
</section>

<%= will_paginate @posts, renderer: 'BootstrapPaginateHelper::LinkRenderer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= static_pages_home_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= posts_path %>">Posts <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= static_pages_contacts_path %>">Contacts</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">      
          <%= link_to 'New post', new_post_path, class: 'btn btn-outline-primary pull-xs-right' %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert alert-<%= name %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <%= render "shared/submenu" %>

          <div class="tag-cloud">
            <h2>Tags</h2>
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, {  include_blank: true }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, class: 'form' %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <%= f.submit t('posts.form.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if post.category.present? %>
        |
        <%= link_to post.category.name, post.category %>
      <% end %>
      |
      <%= link_to 'Edit', edit_post_path(post) %>
      |
      <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
    </small>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'image-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t), class: 'badge badge-success' }.join(' ') %>
  </section>
</article>

app/views/posts/edit.html.erb
<h1><%= t('posts.edit.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('posts.index.title') %></h1>

<%= render @posts %>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/new.html.erb
<h1><%= t('posts.new.title') %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'shared/breadcrumb', category: @post.category %>

<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y")%></time>
      <% if @post.category.present? %>
        |
        <%= link_to @post.category.name, @post.category %>
      <% end %>
      |
      <%= link_to 'Edit', edit_post_path(@post) %>
      |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    </small>
  </section>
  
  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

app/views/shared/_breadcrumb.html.erb
<% if category.present? && category.parent %>
  <ol class="breadcrumb">
    <%= build_breadcrumb(category) %>
  </ol>
<% end %>

app/views/shared/_submenu.html.erb
<div class="submenu">
  <h2>Categories</h2>
  <ul class="nav nav-pills nav-stacked">
    <% Category.roots.each do |category| %>
      <li class="nav-item">
        <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
        <%= render 'shared/submenu_categories', categories: category.root.descendants.arrange %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_submenu_categories.html.erb
<ul class="nav nav-pills nav-stacked nested-nav">
  <% categories.each do |category, children| %>
    <li>
      <%= link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}" %>
      <%= render 'shared/submenu_categories', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/static_pages/contacts.html.erb
<div class"container">
  <h1>Contacts</h1>
  <p>Here should be your contacts</p>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <h1>Welcome to the Tech Blog</h1>
  <p>Here you may learn the rules of this web resource and sign up or log in to access more materials.</p>
</div>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
  <h2>Статей нет</h2>
<% else %>
  <%= render @tag.posts %>
<% end %>

app/views/users/show.html.erb
<div class="col-md-4">
  <h1><%= @user.name %></h1>
  <%= image_tag(user_avatar(@user), size: "100x100", alt: "Photo") %>
  <p><%= mail_to @user.email %></p>
  <p><%= @user.phone %></p>
  <%= link_to 'Edit user' %>
  |
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete  %>
</div>